### ISSUE TITLE
Using dense and gcn_cheby filters

### ISSUE THREAD

**Issue by Ketki-Savle** [yao8839836/text_gcn#30]
Hi, 

I am trying to apply 'dense' and 'gcn_cheby' models in train.py after experimenting with "gcn" model.  This is giving me an error. 

for dense: 

TypeError: Fetch argument <bound method MLP.predict of <models.MLP object at 0x0000011906D46E80>> has invalid type <class 'method'>, must be a string or Tensor. (Can not convert a method into a Tensor or Operation.)

Could you please tell me if there are any instructions to follow. 

Thank you. 

Ketki

**Comment by yao8839836** [comment]
@Ketki-Savle 

Hi Ketki,

These are from the original GCN TensorFlow implementation : https://github.com/tkipf/gcn/blob/master/gcn/train.py

And I can successfully run their code with dense and gcn_cheby. Could you try their code first?

And  I think dense layers could not work for our text graph, because our features are one-hot vectors.

Thanks.

Liang

**Comment by Ketki-Savle** [comment]
Sure.

I think I have made a mistake somewhere because I have made some changes in
constructing the graph.

I will get back to you in case of any issues. For now it's ok if you close
the issue.

Thank you for your help as always. Really happy to cite your work in my
thesis.

Regards,

Ketki

**Comment by yao8839836** [comment]
@Ketki-Savle 

Thank you!
